workflows:
  ios:
    name: iOS Workflow
    max_build_duration: 60
    platform: ios
    description: Build an iOS application
    flutter: stable
    environment:
      vars:
        FLUTTER_PROJECT_PATH: .
    scripts:
      - name: Modify Podfile and install Pods
        script: |
          # Set the correct iOS deployment target in the Podfile
          sed -i '' 's/10.0/13.0/' ios/Podfile

          # Remove existing Pods and Podfile.lock
          rm -rf ios/Pods ios/Podfile.lock ios/Runner.xcworkspace

          # Install dependencies and Pods
          cd ios
          pod install --repo-update

      - name: Build iOS app
        script: |
          flutter build ios --release

    artifacts:
      - build/ios/iphoneos/Runner.app
