workflows:
  ios_build:
    name: iOS Build Workflow
    environment:
      flutter: stable # Specify the Flutter version channel
      xcode: latest # Use the latest version of Xcode
      vars:
        FLUTTER_PROJECT_PATH: . # Path to the Flutter project
    scripts:
      - name: Clean and prepare the environment
        script: |
          echo "Cleaning build artifacts..."
          flutter clean
          echo "Ensuring proper Flutter dependencies..."
          flutter pub get

      - name: Update Podfile and clean Pods
        script: |
          echo "Updating iOS Deployment Target in Podfile to 13.0..."
          sed -i '' 's/10.0/13.0/' ios/Podfile || echo "No iOS deployment target found to update."

          echo "Cleaning old CocoaPods dependencies..."
          rm -rf ios/Pods ios/Podfile.lock ios/Runner.xcworkspace

          echo "Installing updated Pods..."
          cd ios && pod install --repo-update

      - name: Build iOS app
        script: |
          echo "Building Flutter iOS app in release mode..."
          flutter build ios --release

    artifacts:
      - build/ios/iphoneos/Runner.app # Collect the app artifact
    publishing:
      email:
        recipients:
          - tarikulislam4145@gmail.com # Email address to receive the build result
