workflows:
  ios-build:
    name: iOS Build Workflow
    environment:
      vars:
        FLUTTER_BUILD_MODE: "release"
        FLUTTER_BUILD_NAME: "1.0.0"
        FLUTTER_BUILD_NUMBER: "1"
      node: latest
      xcode: latest
    scripts:
      - name: Set up Flutter
        script: |
          flutter --version
          flutter pub get
      - name: Update Podfile and Install Pods
        script: |
          cd ios
          if grep -q "post_install do" Podfile; then
            echo "Merging post_install logic"
            sed -i '' '/post_install do |installer|/a\
            \  installer.pods_project.targets.each do |target|\
            \    target.build_configurations.each do |config|\
            \      config.build_settings[\"IPHONEOS_DEPLOYMENT_TARGET\"] = \"13.0\"\
            \    end\
            \  end' Podfile
          else
            echo "Adding post_install logic"
            echo -e '\npost_install do |installer|' >> Podfile
            echo -e '  installer.pods_project.targets.each do |target|' >> Podfile
            echo -e '    target.build_configurations.each do |config|' >> Podfile
            echo -e '      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "13.0"' >> Podfile
            echo -e '    end' >> Podfile
            echo -e '  end' >> Podfile
            echo -e 'end' >> Podfile
          fi
          pod repo update
          pod install
      - name: Build iOS App
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
