workflows:
  ios-build:
    name: iOS Build Workflow
    environment:
      vars:
        FLUTTER_BUILD_MODE: "release"
        FLUTTER_BUILD_NAME: "1.0.0"
        FLUTTER_BUILD_NUMBER: "1"
      node: latest
      xcode: latest
    scripts:
      - name: Set up Flutter
        script: |
          flutter --version
          flutter pub get
      - name: Update Podfile and Install Pods
        script: |
          cd ios
          cat > Podfile <<EOF
          platform :ios, '13.0'

          # CocoaPods analytics disabled
          ENV['COCOAPODS_DISABLE_STATS'] = 'true'

          # Flutter-specific settings
          load File.join(File.dirname(__FILE__), 'Flutter', 'podhelper.rb')

          target 'Runner' do
            use_frameworks!
            use_modular_headers!

            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end

          post_install do |installer|
            installer.pods_project.targets.each do |target|
              target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
              end
            end
          end
          EOF
          pod repo update
          pod install
      - name: Build iOS App
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
