workflows:
  ios:
    name: Build iOS App
    environment:
      xcode: latest
      cocoapods: latest
    scripts:
      - name: Set CocoaPods Deployment Target
        script: |
          echo "Setting deployment target to iOS 13..."
          sed -i '' '1i\
          platform :ios, "13.0"
          ' Podfile
      - name: Install CocoaPods dependencies
        script: |
          echo "Installing CocoaPods dependencies..."
          rm -rf Pods Podfile.lock
          pod install --repo-update
      - name: Build with Xcode
        script: xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release -sdk iphoneos -archivePath $PWD/build/Runner.xcarchive clean archive
    artifacts:
      - build/Runner.xcarchive
