name: space_texting
version: 1.0.9+9
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  glossy: ^0.0.4
  flutter_svg: ^2.0.10+1
  pinput: ^5.0.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  flutter_multi_formatter: ^2.13.0
  intl_phone_number_input: ^0.7.4
  cloud_firestore: ^5.4.0
  flutter_webrtc: ^0.11.6+hotfix.1
  firebase_messaging: 15.1.0
  giphy_get: ^3.5.6
  socket_io_client: ^3.0.0
  contacts_service: ^0.6.3
  video_player: ^2.9.2
  firebase_storage: ^12.2.0
  file_picker: ^8.0.5
  image: ^4.2.0
  share_plus: ^10.0.0
  sqflite:
  intl:
  network_usage: ^0.0.4
  android_intent_plus: ^5.2.0
  flutter_dotenv: ^5.2.1
  flutter_stripe: ^11.2.0
  url_launcher: ^6.3.1
  flutter_callkit_incoming: ^2.0.4+2
  uuid: ^4.5.1

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/


flutter_assets:
  assets_path: assets/
  output_path: lib/constants/
  filename: assets.dart
