dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: 4.6.6 # Compatible as is
  glossy: ^0.0.4
  flutter_svg: ^1.0.3 # Compatible with older Flutter and iOS 12
  pinput: ^4.2.0 # Downgrade to a version compatible with older iOS
  image_picker: ^0.8.4+8 # Stable and compatible with iOS 12
  permission_handler: ^9.2.0 # Earlier versions support iOS 12
  firebase_core: ^2.9.0 # Compatible version
  firebase_auth: ^4.5.3 # Compatible version
  flutter_multi_formatter: ^2.1.0 # Earlier version for iOS 12 compatibility
  intl_phone_number_input: ^0.7.0 # Compatible with iOS 12
  cloud_firestore: ^3.5.0 # Earlier version for iOS 12
  flutter_webrtc: ^0.7.1 # Downgrade for iOS 12 support
  firebase_messaging: ^14.0.3 # Earlier version compatible with iOS 12
  giphy_get: ^3.2.0 # Older version with wider compatibility
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  contacts_service: ^0.6.2 # Compatible version
  video_player: ^2.1.15 # Compatible with iOS 12
  firebase_storage: ^11.0.0 # Earlier version for iOS 12
  file_picker: ^4.2.7 # Compatible version
  image: ^3.0.0 # Downgrade for iOS 12
  share_plus: ^6.0.0 # Older version supporting iOS 12
  sqflite: ^2.0.2+1 # Compatible as is
  intl: ^0.17.0 # Compatible version
  network_usage: ^0.0.4
  android_intent_plus: ^4.0.0
  flutter_dotenv: ^3.1.0
  flutter_stripe: ^5.0.0 # Significant downgrade for iOS 12
  url_launcher: ^6.0.9
  flutter_callkit_incoming: ^1.1.0 # Downgrade to older version
  uuid: ^3.0.4

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
