name: Build iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Fix Invalid Dart Package Name (if necessary)
      - name: Fix Package Name
        run: |
          if grep -q '^name: space-texting$' pubspec.yaml; then
            sed -i '' 's/^name: space-texting$/name: space_texting/' pubspec.yaml
            echo "Fixed invalid Dart package name in pubspec.yaml."
          fi

      # Step 3: Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      # Step 4: Install Ruby
      - name: Install Ruby
        run: |
          brew install ruby
          echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.bash_profile
          source ~/.bash_profile

      # Step 5: Install CocoaPods
      - name: Install CocoaPods
        run: sudo gem install cocoapods

      # Step 6: Install Flutter Dependencies
      - name: Install Flutter Dependencies
        run: flutter pub get

      # Step 7: Clean and Recreate iOS Podfile
      - name: Recreate Podfile
        run: |
          flutter clean
          flutter create .
          cd ios
          rm -rf Podfile Podfile.lock Pods
          pod init
          echo "platform :ios, '12.0'" > Podfile
          echo "workspace 'Runner.xcworkspace'" >> Podfile
          echo "use_frameworks!" >> Podfile
          pod install

      # Step 8: Build iOS
      - name: Build iOS
        run: flutter build ios --release --no-codesign

      # Optional: Verify Dart Version
      - name: Check Dart Version
        run: dart --version
