name: Build iOS App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      # Step 1: Checkout your code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable' # Replace with your version if not using "stable"

      # Step 3: Install CocoaPods
      - name: Install CocoaPods
        run: sudo gem install cocoapods

      # Step 4: Fetch Flutter dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Step 5: Build the iOS app
      - name: Build iOS Release
        run: flutter build ios --release
