name: Build iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      # Step 3: Install Ruby
      - name: Install Ruby
        run: |
          brew install ruby
          echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.bash_profile
          source ~/.bash_profile

      # Step 4: Install CocoaPods
      - name: Install CocoaPods
        run: sudo gem install cocoapods

      # Step 5: Clean Flutter Project and Install Dependencies
      - name: Clean Flutter Project and Install Dependencies
        run: |
          flutter clean
          flutter pub get

      # Step 6: Ensure Podfile is Correct (Configure Firebase & Firestore)
      - name: Update Podfile for Firebase
        run: |
          echo "platform :ios, '13.0'" > ios/Podfile
          echo "use_frameworks!" >> ios/Podfile
          echo "pod 'Firebase/Core', '~> 10.0'" >> ios/Podfile
          echo "pod 'Firebase/Firestore', '~> 10.0'" >> ios/Podfile
          echo "pod 'cloud_firestore', '~> 4.0.0'" >> ios/Podfile
          flutter clean

      # Step 7: Install CocoaPods Dependencies
      - name: Install CocoaPods Dependencies
        run: |
          cd ios
          pod install --repo-update

      # Step 8: Build iOS App (Release)
      - name: Build iOS App (Release)
        run: flutter build ios --release --no-codesign
