name: iOS Build and Fix Issues

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on PRs to main branch

jobs:
  build-ios:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Flutter SDK
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # Specify Flutter version

      # Step 3: Install Ruby for CocoaPods
      - name: Set up Ruby for CocoaPods
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      # Step 4: Install CocoaPods and Update Repos
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod repo update

      # Step 5: Fetch Flutter Dependencies
      - name: Fetch Flutter Dependencies
        run: |
          flutter clean
          flutter pub get

      # Step 6: Modify Podfile and Install Pods
      - name: Set Platform to iOS 13 and Install Pods
        run: |
          cd ios
          sed -i '' 's/platform :ios, .*/platform :ios, "13.0"/g' Podfile  # Set platform to iOS 13.0
          pod install
        shell: bash

      # Step 7: Build iOS App
      - name: Build iOS App
        run: flutter build ios --release

      # Step 8: Upload Build Artifacts (Optional)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-release-build
          path: build/ios/iphoneos/Runner.app
