name: Build iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      # Step 3: Install Ruby
      - name: Install Ruby
        run: |
          brew install ruby
          echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.bash_profile
          source ~/.bash_profile

      # Step 4: Install CocoaPods
      - name: Install CocoaPods
        run: sudo gem install cocoapods

      # Step 5: Install Flutter Dependencies
      - name: Install Flutter Dependencies
        run: flutter pub get

      # Step 6: Initialize iOS Platform (Regenerate Podfile)
      - name: Ensure iOS Directory and Podfile
        run: |
          flutter clean
          flutter create .
          cd ios
          rm -rf Podfile.lock Pods
          pod init

      # Step 7: Add Platform and Dependencies to Podfile
      - name: Configure Podfile
        run: |
          echo "platform :ios, '12.0'" > ios/Podfile
          echo "workspace 'Runner.xcworkspace'" >> ios/Podfile
          echo "use_frameworks!" >> ios/Podfile

      # Step 8: Install Pods
      - name: Install Pods
        run: |
          cd ios
          pod install

      # Step 9: Build iOS
      - name: Build iOS
        run: flutter build ios --release --no-codesign

      # Optional: Verify Dart Version
      - name: Check Dart Version
        run: dart --version
