name: Build iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      # Step 3: Install Ruby
      - name: Install Ruby
        run: |
          brew install ruby
          echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.bash_profile
          source ~/.bash_profile

      # Step 4: Install CocoaPods
      - name: Install CocoaPods
        run: sudo gem install cocoapods

      # Step 5: Install Flutter Dependencies
      - name: Install Flutter Dependencies
        run: flutter pub get

      # Step 6: Clean project and regenerate iOS files
      - name: Clean Flutter Project and Regenerate iOS Files
        run: |
          flutter clean
          flutter create .
          cd ios
          rm -rf Podfile.lock Pods
          pod init

      # Step 7: Update and Configure Podfile
      - name: Update and Configure Podfile
        run: |
          echo "platform :ios, '13.0'" > ios/Podfile
          echo "workspace 'Runner.xcworkspace'" >> ios/Podfile
          echo "use_frameworks!" >> ios/Podfile
          echo "pod 'Firebase/Core', '~> 10.0'" >> ios/Podfile
          echo "pod 'Firebase/Firestore', '~> 10.0'" >> ios/Podfile
          echo "pod 'cloud_firestore', '~> 4.0.0'" >> ios/Podfile

      # Step 8: Install Pods with repo update
      - name: Install Pods
        run: |
          cd ios
          pod install --repo-update

      # Step 9: Build iOS
      - name: Build iOS
        run: flutter build ios --release --no-codesign

      # Optional: Check Dart Version
      - name: Check Dart Version
        run: dart --version
